general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
    
      cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
      target: 'https://api.cf.us10-001.hana.ondemand.com/'
      org: '30c12a2ctrial_mytrial-mrt'
      space: 'DEV'
      credentialsId: 'CF_CREDENTIALSID'
