general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:    
      cfApiEndpoint: 'https://api.cf.eu10-004.hana.ondemand.com'
      target: 'https://api.cf.eu10-004.hana.ondemand.com/'
      org: 'Simac IT NL B.V._devops-toolchain-5nhqwfg7'
      space: 'DevOps'
      credentialsId: 'CF_CREDENTIALSID'
